/*
 * NGINX Unit 1.31.1
 *
 * NGINX Unit is a lightweight and versatile application runtime that provides the essential components for your web application as a single open-source server: running application code, serving static assets, handling TLS and request routing.   **Important**: Ufnit's API is designed to expose any part of its configuration as an addressable endpoint.  Suppose a JSON object is stored at `/config/listeners/`:   ```json { \"*:8080\": { \"pass\": \"applications/wp_emea_dev\" } } ```  Here, `/config/listeners/_*:8080` and `/config/listeners/_*:8080/pass` are also endpoints.  Generally, object options are addressable by their names, array items—by their indexes (`/array/0/`).    **Note**: By default, Unit is configured through a UNIX domain socket. To use this specification with OpenAPI tools interactively, [start](https://unit.nginx.org/howto/source/#source-startup) Unit with a TCP port as the control socket.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: unit-owner@nginx.org
 * Generated by: https://openapi-generator.tech
 */

use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use std::pin::Pin;
use std::rc::Rc;

use futures::Future;
use hyper;

use super::request as __internal_request;
use super::{configuration, Error};

pub struct ConfigApiClient<C: hyper::client::connect::Connect>
where
    C: Clone + std::marker::Send + Sync + 'static,
{
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::connect::Connect> ConfigApiClient<C>
where
    C: Clone + std::marker::Send + Sync,
{
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> ConfigApiClient<C> {
        ConfigApiClient { configuration }
    }
}

pub trait ConfigApi {
    fn delete_access_log(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_access_log_format(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_access_log_path(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_application(
        &self,
        app_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_applications(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_config(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_forwarded_recursive(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_forwarded_source(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_forwarded_sources(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_forwared(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_tls(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_tls_certificate(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_tls_certificates(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_tls_conf_commands(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_tls_session(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_tls_session_ticket(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listener_tls_session_tickets(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_listeners(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_routes(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_discard_unsafe_fields(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_http(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_http_body_read_timeout(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_http_header_read_timeout(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_http_idle_timeout(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_http_max_body_size(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_http_send_timeout(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_http_static(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_http_static_mime_type(
        &self,
        mime_type: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_http_static_mime_types(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_log_route(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn delete_settings_server_version(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn get_access_log(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigAccessLog, Error>>>>;
    fn get_access_log_format(&self) -> Pin<Box<dyn Future<Output = Result<String, Error>>>>;
    fn get_access_log_path(&self) -> Pin<Box<dyn Future<Output = Result<String, Error>>>>;
    fn get_application(
        &self,
        app_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigApplication, Error>>>>;
    fn get_applications(
        &self,
    ) -> Pin<
        Box<dyn Future<Output = Result<::std::collections::HashMap<String, crate::models::ConfigApplication>, Error>>>,
    >;
    fn get_config(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::Config, Error>>>>;
    fn get_listener(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListener, Error>>>>;
    fn get_listener_forwarded(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerForwarded, Error>>>>;
    fn get_listener_forwarded_client_ip(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>>;
    fn get_listener_forwarded_protocol(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>>;
    fn get_listener_forwarded_recursive(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<bool, Error>>>>;
    fn get_listener_forwarded_source(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>>;
    fn get_listener_pass(&self, listener_name: &str) -> Pin<Box<dyn Future<Output = Result<String, Error>>>>;
    fn get_listener_tls(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerTls, Error>>>>;
    fn get_listener_tls_certificate(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>>;
    fn get_listener_tls_session(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerTlsSession, Error>>>>;
    fn get_listener_tls_session_ticket(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>>;
    fn get_listeners(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, crate::models::ConfigListener>, Error>>>>;
    fn get_routes(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigRoutes, Error>>>>;
    fn get_settings(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigSettings, Error>>>>;
    fn get_settings_discard_unsafe_fields(&self) -> Pin<Box<dyn Future<Output = Result<bool, Error>>>>;
    fn get_settings_http(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigSettingsHttp, Error>>>>;
    fn get_settings_http_body_read_timeout(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>>;
    fn get_settings_http_header_read_timeout(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>>;
    fn get_settings_http_idle_timeout(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>>;
    fn get_settings_http_max_body_size(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>>;
    fn get_settings_http_send_timeout(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>>;
    fn get_settings_http_static(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigSettingsHttpStatic, Error>>>>;
    fn get_settings_http_static_mime_type(
        &self,
        mime_type: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigSettingsHttpStaticMimeType, Error>>>>;
    fn get_settings_http_static_mime_types(
        &self,
    ) -> Pin<
        Box<
            dyn Future<
                Output = Result<
                    ::std::collections::HashMap<String, crate::models::ConfigSettingsHttpStaticMimeType>,
                    Error,
                >,
            >,
        >,
    >;
    fn get_settings_log_route(&self) -> Pin<Box<dyn Future<Output = Result<bool, Error>>>>;
    fn get_settings_server_version(&self) -> Pin<Box<dyn Future<Output = Result<bool, Error>>>>;
    fn insert_listener_forwarded_source(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn insert_listener_tls_certificate(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn insert_listener_tls_session_ticket(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn list_listener_forwarded_sources(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::StringOrStringArray, Error>>>>;
    fn list_listener_tls_certificates(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerTlsCertificate, Error>>>>;
    fn list_listener_tls_conf_commands(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn list_listener_tls_session_tickets(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerTlsSessionTickets, Error>>>>;
    fn update_access_log(
        &self,
        config_access_log: crate::models::ConfigAccessLog,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_access_log_format(
        &self,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_access_log_path(
        &self,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_application(
        &self,
        app_name: &str,
        config_application: crate::models::ConfigApplication,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_applications(
        &self,
        request_body: ::std::collections::HashMap<String, crate::models::ConfigApplication>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_config(
        &self,
        config: crate::models::Config,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener(
        &self,
        listener_name: &str,
        config_listener: crate::models::ConfigListener,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_forwarded(
        &self,
        listener_name: &str,
        config_listener_forwarded: crate::models::ConfigListenerForwarded,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_forwarded_client_ip(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_forwarded_protocol(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_forwarded_recursive(
        &self,
        listener_name: &str,
        body: bool,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_forwarded_source(
        &self,
        listener_name: &str,
        array_index: i32,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_forwarded_sources(
        &self,
        listener_name: &str,
        string_or_string_array: Option<crate::models::StringOrStringArray>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_pass(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_tls(
        &self,
        listener_name: &str,
        config_listener_tls: crate::models::ConfigListenerTls,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_tls_certificate(
        &self,
        listener_name: &str,
        array_index: i32,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_tls_certificates(
        &self,
        listener_name: &str,
        string_or_string_array: Option<crate::models::StringOrStringArray>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_tls_conf_commands(
        &self,
        listener_name: &str,
        request_body: ::std::collections::HashMap<String, String>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_tls_session(
        &self,
        listener_name: &str,
        config_listener_tls_session: crate::models::ConfigListenerTlsSession,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_tls_session_ticket(
        &self,
        listener_name: &str,
        array_index: i32,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listener_tls_session_tickets(
        &self,
        listener_name: &str,
        config_listener_tls_session_tickets: Option<crate::models::ConfigListenerTlsSessionTickets>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_listeners(
        &self,
        request_body: ::std::collections::HashMap<String, crate::models::ConfigListener>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_routes(
        &self,
        config_routes: Option<crate::models::ConfigRoutes>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings(
        &self,
        config_settings: crate::models::ConfigSettings,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_discard_unsafe_fields(
        &self,
        body: bool,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_http(
        &self,
        config_settings_http: crate::models::ConfigSettingsHttp,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_http_body_read_timeout(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_http_header_read_timeout(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_http_idle_timeout(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_http_max_body_size(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_http_send_timeout(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_http_static(
        &self,
        config_settings_http_static: crate::models::ConfigSettingsHttpStatic,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_http_static_mime_type(
        &self,
        mime_type: &str,
        config_settings_http_static_mime_type: Option<crate::models::ConfigSettingsHttpStaticMimeType>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_http_static_mime_types(
        &self,
        request_body: ::std::collections::HashMap<String, crate::models::ConfigSettingsHttpStaticMimeType>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_log_route(
        &self,
        body: bool,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
    fn update_settings_server_version(
        &self,
        body: bool,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>>;
}

impl<C: hyper::client::connect::Connect> ConfigApi for ConfigApiClient<C>
where
    C: Clone + std::marker::Send + Sync,
{
    #[allow(unused_mut)]
    fn delete_access_log(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::DELETE, "/config/access_log".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_access_log_format(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::DELETE, "/config/access_log/format".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_access_log_path(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::DELETE, "/config/access_log/path".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_application(
        &self,
        app_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::DELETE, "/config/applications/{appName}".to_string());
        req = req.with_path_param("appName".to_string(), app_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_applications(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::DELETE, "/config/applications".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_config(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::DELETE, "/config".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::DELETE, "/config/listeners/{listenerName}".to_string());
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_forwarded_recursive(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/forwarded/recursive".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_forwarded_source(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/forwarded/source/{arrayIndex}".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_path_param("arrayIndex".to_string(), array_index.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_forwarded_sources(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/forwarded/source".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_forwared(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/forwarded".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_tls(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/tls".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_tls_certificate(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/tls/certificate/{arrayIndex}".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_path_param("arrayIndex".to_string(), array_index.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_tls_certificates(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/tls/certificate".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_tls_conf_commands(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/tls/conf_commands".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_tls_session(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/tls/session".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_tls_session_ticket(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/tls/session/tickets/{arrayIndex}".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_path_param("arrayIndex".to_string(), array_index.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listener_tls_session_tickets(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/listeners/{listenerName}/tls/session/tickets".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_listeners(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::DELETE, "/config/listeners".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_routes(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::DELETE, "/config/routes".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::DELETE, "/config/settings".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_discard_unsafe_fields(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/settings/http/discard_unsafe_fields".to_string(),
        );

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_http(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::DELETE, "/config/settings/http".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_http_body_read_timeout(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/settings/http/body_read_timeout".to_string(),
        );

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_http_header_read_timeout(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/settings/http/header_read_timeout".to_string(),
        );

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_http_idle_timeout(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::DELETE, "/config/settings/http/idle_timeout".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_http_max_body_size(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::DELETE, "/config/settings/http/max_body_size".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_http_send_timeout(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::DELETE, "/config/settings/http/send_timeout".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_http_static(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::DELETE, "/config/settings/http/static".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_http_static_mime_type(
        &self,
        mime_type: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/settings/http/static/mime_types/{mimeType}".to_string(),
        );
        req = req.with_path_param("mimeType".to_string(), mime_type.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_http_static_mime_types(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/settings/http/static/mime_types".to_string(),
        );

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_log_route(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::DELETE, "/config/settings/http/log_route".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn delete_settings_server_version(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::DELETE,
            "/config/settings/http/server_version".to_string(),
        );

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_access_log(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigAccessLog, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config/access_log".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_access_log_format(&self) -> Pin<Box<dyn Future<Output = Result<String, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config/access_log/format".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_access_log_path(&self) -> Pin<Box<dyn Future<Output = Result<String, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config/access_log/path".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_application(
        &self,
        app_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigApplication, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/config/applications/{appName}".to_string());
        req = req.with_path_param("appName".to_string(), app_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_applications(
        &self,
    ) -> Pin<
        Box<dyn Future<Output = Result<::std::collections::HashMap<String, crate::models::ConfigApplication>, Error>>>,
    > {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config/applications".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_config(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::Config, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListener, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/config/listeners/{listenerName}".to_string());
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_forwarded(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerForwarded, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/forwarded".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_forwarded_client_ip(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/forwarded/client_ip".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_forwarded_protocol(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/forwarded/protocol".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_forwarded_recursive(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<bool, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/forwarded/recursive".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_forwarded_source(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/forwarded/source/{arrayIndex}".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_path_param("arrayIndex".to_string(), array_index.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_pass(&self, listener_name: &str) -> Pin<Box<dyn Future<Output = Result<String, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/config/listeners/{listenerName}/pass".to_string());
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_tls(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerTls, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/config/listeners/{listenerName}/tls".to_string());
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_tls_certificate(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/tls/certificate/{arrayIndex}".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_path_param("arrayIndex".to_string(), array_index.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_tls_session(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerTlsSession, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/tls/session".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listener_tls_session_ticket(
        &self,
        listener_name: &str,
        array_index: i32,
    ) -> Pin<Box<dyn Future<Output = Result<String, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/tls/session/tickets/{arrayIndex}".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_path_param("arrayIndex".to_string(), array_index.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_listeners(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, crate::models::ConfigListener>, Error>>>>
    {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config/listeners".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_routes(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigRoutes, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config/routes".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigSettings, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config/settings".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_discard_unsafe_fields(&self) -> Pin<Box<dyn Future<Output = Result<bool, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/settings/http/discard_unsafe_fields".to_string(),
        );

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_http(&self) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigSettingsHttp, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config/settings/http".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_http_body_read_timeout(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/settings/http/body_read_timeout".to_string(),
        );

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_http_header_read_timeout(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/settings/http/header_read_timeout".to_string(),
        );

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_http_idle_timeout(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/config/settings/http/idle_timeout".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_http_max_body_size(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/config/settings/http/max_body_size".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_http_send_timeout(&self) -> Pin<Box<dyn Future<Output = Result<i32, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/config/settings/http/send_timeout".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_http_static(
        &self,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigSettingsHttpStatic, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::GET, "/config/settings/http/static".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_http_static_mime_type(
        &self,
        mime_type: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigSettingsHttpStaticMimeType, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/settings/http/static/mime_types/{mimeType}".to_string(),
        );
        req = req.with_path_param("mimeType".to_string(), mime_type.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_http_static_mime_types(
        &self,
    ) -> Pin<
        Box<
            dyn Future<
                Output = Result<
                    ::std::collections::HashMap<String, crate::models::ConfigSettingsHttpStaticMimeType>,
                    Error,
                >,
            >,
        >,
    > {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/settings/http/static/mime_types".to_string(),
        );

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_log_route(&self) -> Pin<Box<dyn Future<Output = Result<bool, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/config/settings/http/log_route".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn get_settings_server_version(&self) -> Pin<Box<dyn Future<Output = Result<bool, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::GET, "/config/settings/http/server_version".to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn insert_listener_forwarded_source(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/config/listeners/{listenerName}/forwarded/source".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn insert_listener_tls_certificate(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/config/listeners/{listenerName}/tls/certificate".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn insert_listener_tls_session_ticket(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::POST,
            "/config/listeners/{listenerName}/tls/session/tickets".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn list_listener_forwarded_sources(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::StringOrStringArray, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/forwarded/source".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn list_listener_tls_certificates(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerTlsCertificate, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/tls/certificate".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn list_listener_tls_conf_commands(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/tls/conf_commands".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn list_listener_tls_session_tickets(
        &self,
        listener_name: &str,
    ) -> Pin<Box<dyn Future<Output = Result<crate::models::ConfigListenerTlsSessionTickets, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::GET,
            "/config/listeners/{listenerName}/tls/session/tickets".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_access_log(
        &self,
        config_access_log: crate::models::ConfigAccessLog,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config/access_log".to_string());
        req = req.with_body_param(config_access_log);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_access_log_format(
        &self,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config/access_log/format".to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_access_log_path(
        &self,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config/access_log/path".to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_application(
        &self,
        app_name: &str,
        config_application: crate::models::ConfigApplication,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/config/applications/{appName}".to_string());
        req = req.with_path_param("appName".to_string(), app_name.to_string());
        req = req.with_body_param(config_application);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_applications(
        &self,
        request_body: ::std::collections::HashMap<String, crate::models::ConfigApplication>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config/applications".to_string());
        req = req.with_body_param(request_body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_config(
        &self,
        config: crate::models::Config,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config".to_string());
        req = req.with_body_param(config);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener(
        &self,
        listener_name: &str,
        config_listener: crate::models::ConfigListener,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/config/listeners/{listenerName}".to_string());
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(config_listener);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_forwarded(
        &self,
        listener_name: &str,
        config_listener_forwarded: crate::models::ConfigListenerForwarded,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/forwarded".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(config_listener_forwarded);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_forwarded_client_ip(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/forwarded/client_ip".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_forwarded_protocol(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/forwarded/protocol".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_forwarded_recursive(
        &self,
        listener_name: &str,
        body: bool,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/forwarded/recursive".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_forwarded_source(
        &self,
        listener_name: &str,
        array_index: i32,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/forwarded/source/{arrayIndex}".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_path_param("arrayIndex".to_string(), array_index.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_forwarded_sources(
        &self,
        listener_name: &str,
        string_or_string_array: Option<crate::models::StringOrStringArray>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/forwarded/source".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(string_or_string_array);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_pass(
        &self,
        listener_name: &str,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/config/listeners/{listenerName}/pass".to_string());
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_tls(
        &self,
        listener_name: &str,
        config_listener_tls: crate::models::ConfigListenerTls,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/config/listeners/{listenerName}/tls".to_string());
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(config_listener_tls);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_tls_certificate(
        &self,
        listener_name: &str,
        array_index: i32,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/tls/certificate/{arrayIndex}".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_path_param("arrayIndex".to_string(), array_index.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_tls_certificates(
        &self,
        listener_name: &str,
        string_or_string_array: Option<crate::models::StringOrStringArray>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/tls/certificate".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(string_or_string_array);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_tls_conf_commands(
        &self,
        listener_name: &str,
        request_body: ::std::collections::HashMap<String, String>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/tls/conf_commands".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(request_body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_tls_session(
        &self,
        listener_name: &str,
        config_listener_tls_session: crate::models::ConfigListenerTlsSession,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/tls/session".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(config_listener_tls_session);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_tls_session_ticket(
        &self,
        listener_name: &str,
        array_index: i32,
        body: &str,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/tls/session/tickets/{arrayIndex}".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_path_param("arrayIndex".to_string(), array_index.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listener_tls_session_tickets(
        &self,
        listener_name: &str,
        config_listener_tls_session_tickets: Option<crate::models::ConfigListenerTlsSessionTickets>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/listeners/{listenerName}/tls/session/tickets".to_string(),
        );
        req = req.with_path_param("listenerName".to_string(), listener_name.to_string());
        req = req.with_body_param(config_listener_tls_session_tickets);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_listeners(
        &self,
        request_body: ::std::collections::HashMap<String, crate::models::ConfigListener>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config/listeners".to_string());
        req = req.with_body_param(request_body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_routes(
        &self,
        config_routes: Option<crate::models::ConfigRoutes>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config/routes".to_string());
        req = req.with_body_param(config_routes);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings(
        &self,
        config_settings: crate::models::ConfigSettings,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config/settings".to_string());
        req = req.with_body_param(config_settings);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_discard_unsafe_fields(
        &self,
        body: bool,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/settings/http/discard_unsafe_fields".to_string(),
        );
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_http(
        &self,
        config_settings_http: crate::models::ConfigSettingsHttp,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config/settings/http".to_string());
        req = req.with_body_param(config_settings_http);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_http_body_read_timeout(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/settings/http/body_read_timeout".to_string(),
        );
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_http_header_read_timeout(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/settings/http/header_read_timeout".to_string(),
        );
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_http_idle_timeout(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/config/settings/http/idle_timeout".to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_http_max_body_size(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/config/settings/http/max_body_size".to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_http_send_timeout(
        &self,
        body: i32,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/config/settings/http/send_timeout".to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_http_static(
        &self,
        config_settings_http_static: crate::models::ConfigSettingsHttpStatic,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(hyper::Method::PUT, "/config/settings/http/static".to_string());
        req = req.with_body_param(config_settings_http_static);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_http_static_mime_type(
        &self,
        mime_type: &str,
        config_settings_http_static_mime_type: Option<crate::models::ConfigSettingsHttpStaticMimeType>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/settings/http/static/mime_types/{mimeType}".to_string(),
        );
        req = req.with_path_param("mimeType".to_string(), mime_type.to_string());
        req = req.with_body_param(config_settings_http_static_mime_type);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_http_static_mime_types(
        &self,
        request_body: ::std::collections::HashMap<String, crate::models::ConfigSettingsHttpStaticMimeType>,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req = __internal_request::Request::new(
            hyper::Method::PUT,
            "/config/settings/http/static/mime_types".to_string(),
        );
        req = req.with_body_param(request_body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_log_route(
        &self,
        body: bool,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/config/settings/http/log_route".to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    #[allow(unused_mut)]
    fn update_settings_server_version(
        &self,
        body: bool,
    ) -> Pin<Box<dyn Future<Output = Result<::std::collections::HashMap<String, String>, Error>>>> {
        let mut req =
            __internal_request::Request::new(hyper::Method::PUT, "/config/settings/http/server_version".to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }
}
