/*
 * NGINX Unit 1.31.1
 *
 * NGINX Unit is a lightweight and versatile application runtime that provides the essential components for your web application as a single open-source server: running application code, serving static assets, handling TLS and request routing.   **Important**: Ufnit's API is designed to expose any part of its configuration as an addressable endpoint.  Suppose a JSON object is stored at `/config/listeners/`:   ```json { \"*:8080\": { \"pass\": \"applications/wp_emea_dev\" } } ```  Here, `/config/listeners/_*:8080` and `/config/listeners/_*:8080/pass` are also endpoints.  Generally, object options are addressable by their names, array items—by their indexes (`/array/0/`).    **Note**: By default, Unit is configured through a UNIX domain socket. To use this specification with OpenAPI tools interactively, [start](https://unit.nginx.org/howto/source/#source-startup) Unit with a TCP port as the control socket.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: unit-owner@nginx.org
 * Generated by: https://openapi-generator.tech
 */

/// CertBundleChainCertSubj : An object that represents a certificate's subject.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CertBundleChainCertSubj {
    #[serde(rename = "common_name", skip_serializing_if = "Option::is_none")]
    pub common_name: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "state_or_province", skip_serializing_if = "Option::is_none")]
    pub state_or_province: Option<String>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    /// An array of strings.
    #[serde(rename = "alt_names", skip_serializing_if = "Option::is_none")]
    pub alt_names: Option<Vec<String>>,
}

impl CertBundleChainCertSubj {
    /// An object that represents a certificate's subject.
    pub fn new() -> CertBundleChainCertSubj {
        CertBundleChainCertSubj {
            common_name: None,
            country: None,
            state_or_province: None,
            organization: None,
            alt_names: None,
        }
    }
}
