/*
 * NGINX Unit 1.31.1
 *
 * NGINX Unit is a lightweight and versatile application runtime that provides the essential components for your web application as a single open-source server: running application code, serving static assets, handling TLS and request routing.   **Important**: Ufnit's API is designed to expose any part of its configuration as an addressable endpoint.  Suppose a JSON object is stored at `/config/listeners/`:   ```json { \"*:8080\": { \"pass\": \"applications/wp_emea_dev\" } } ```  Here, `/config/listeners/_*:8080` and `/config/listeners/_*:8080/pass` are also endpoints.  Generally, object options are addressable by their names, array items—by their indexes (`/array/0/`).    **Note**: By default, Unit is configured through a UNIX domain socket. To use this specification with OpenAPI tools interactively, [start](https://unit.nginx.org/howto/source/#source-startup) Unit with a TCP port as the control socket.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: unit-owner@nginx.org
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigApplicationCommonIsolationNamespaces {
    /// Creates a new cgroup namespace for the app.
    #[serde(rename = "cgroup", skip_serializing_if = "Option::is_none")]
    pub cgroup: Option<bool>,
    /// Creates a new user namespace for the app.
    #[serde(rename = "credential", skip_serializing_if = "Option::is_none")]
    pub credential: Option<bool>,
    /// Creates a new mount namespace for the app.
    #[serde(rename = "mount", skip_serializing_if = "Option::is_none")]
    pub mount: Option<bool>,
    /// Creates a new network namespace for the app.
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<bool>,
    /// Creates a new PID namespace for the app.
    #[serde(rename = "pid", skip_serializing_if = "Option::is_none")]
    pub pid: Option<bool>,
    /// Creates a new UTS namespace for the app.
    #[serde(rename = "uname", skip_serializing_if = "Option::is_none")]
    pub uname: Option<bool>,
}

impl ConfigApplicationCommonIsolationNamespaces {
    pub fn new() -> ConfigApplicationCommonIsolationNamespaces {
        ConfigApplicationCommonIsolationNamespaces {
            cgroup: None,
            credential: None,
            mount: None,
            network: None,
            pid: None,
            uname: None,
        }
    }
}
