/*
 * NGINX Unit 1.31.1
 *
 * NGINX Unit is a lightweight and versatile application runtime that provides the essential components for your web application as a single open-source server: running application code, serving static assets, handling TLS and request routing.   **Important**: Ufnit's API is designed to expose any part of its configuration as an addressable endpoint.  Suppose a JSON object is stored at `/config/listeners/`:   ```json { \"*:8080\": { \"pass\": \"applications/wp_emea_dev\" } } ```  Here, `/config/listeners/_*:8080` and `/config/listeners/_*:8080/pass` are also endpoints.  Generally, object options are addressable by their names, array items—by their indexes (`/array/0/`).    **Note**: By default, Unit is configured through a UNIX domain socket. To use this specification with OpenAPI tools interactively, [start](https://unit.nginx.org/howto/source/#source-startup) Unit with a TCP port as the control socket.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: unit-owner@nginx.org
 * Generated by: https://openapi-generator.tech
 */

/// Config : The entire /config section of the API.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Config {
    #[serde(rename = "access_log", skip_serializing_if = "Option::is_none")]
    pub access_log: Option<Box<crate::models::ConfigAccessLog>>,
    /// An object whose options define individual applications.
    #[serde(rename = "applications", skip_serializing_if = "Option::is_none")]
    pub applications: Option<::std::collections::HashMap<String, crate::models::ConfigApplication>>,
    #[serde(rename = "routes", skip_serializing_if = "Option::is_none")]
    pub routes: Option<Box<crate::models::ConfigRoutes>>,
    /// An object whose options are listeners.
    #[serde(rename = "listeners", skip_serializing_if = "Option::is_none")]
    pub listeners: Option<::std::collections::HashMap<String, crate::models::ConfigListener>>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<crate::models::ConfigSettings>>,
}

impl Config {
    /// The entire /config section of the API.
    pub fn new() -> Config {
        Config {
            access_log: None,
            applications: None,
            routes: None,
            listeners: None,
            settings: None,
        }
    }
}
