/*
 * NGINX Unit 1.31.1
 *
 * NGINX Unit is a lightweight and versatile application runtime that provides the essential components for your web application as a single open-source server: running application code, serving static assets, handling TLS and request routing.   **Important**: Ufnit's API is designed to expose any part of its configuration as an addressable endpoint.  Suppose a JSON object is stored at `/config/listeners/`:   ```json { \"*:8080\": { \"pass\": \"applications/wp_emea_dev\" } } ```  Here, `/config/listeners/_*:8080` and `/config/listeners/_*:8080/pass` are also endpoints.  Generally, object options are addressable by their names, array items—by their indexes (`/array/0/`).    **Note**: By default, Unit is configured through a UNIX domain socket. To use this specification with OpenAPI tools interactively, [start](https://unit.nginx.org/howto/source/#source-startup) Unit with a TCP port as the control socket.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: unit-owner@nginx.org
 * Generated by: https://openapi-generator.tech
 */

/// ConfigApplicationCommonIsolationAutomount : Controls mount behavior if rootfs is enabled.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigApplicationCommonIsolationAutomount {
    /// Controls whether the language runtime dependencies are automounted.
    #[serde(rename = "language_deps", skip_serializing_if = "Option::is_none")]
    pub language_deps: Option<bool>,
    /// Controls whether the procfs is automounted.
    #[serde(rename = "procfs", skip_serializing_if = "Option::is_none")]
    pub procfs: Option<bool>,
    /// Controls whether the tmpfs is automounted.
    #[serde(rename = "tmpfs", skip_serializing_if = "Option::is_none")]
    pub tmpfs: Option<bool>,
}

impl ConfigApplicationCommonIsolationAutomount {
    /// Controls mount behavior if rootfs is enabled.
    pub fn new() -> ConfigApplicationCommonIsolationAutomount {
        ConfigApplicationCommonIsolationAutomount {
            language_deps: None,
            procfs: None,
            tmpfs: None,
        }
    }
}
