/*
 * NGINX Unit 1.31.1
 *
 * NGINX Unit is a lightweight and versatile application runtime that provides the essential components for your web application as a single open-source server: running application code, serving static assets, handling TLS and request routing.   **Important**: Ufnit's API is designed to expose any part of its configuration as an addressable endpoint.  Suppose a JSON object is stored at `/config/listeners/`:   ```json { \"*:8080\": { \"pass\": \"applications/wp_emea_dev\" } } ```  Here, `/config/listeners/_*:8080` and `/config/listeners/_*:8080/pass` are also endpoints.  Generally, object options are addressable by their names, array items—by their indexes (`/array/0/`).    **Note**: By default, Unit is configured through a UNIX domain socket. To use this specification with OpenAPI tools interactively, [start](https://unit.nginx.org/howto/source/#source-startup) Unit with a TCP port as the control socket.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: unit-owner@nginx.org
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigApplicationPythonAllOfTargets {
    /// Target's module name.
    #[serde(rename = "module")]
    pub module: String,
    /// Name of the `module`-based callable that Unit runs as the target.
    #[serde(rename = "callable", skip_serializing_if = "Option::is_none")]
    pub callable: Option<String>,
    /// SCRIPT_NAME context value for WSGI or the root_path context value for ASGI.
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
}

impl ConfigApplicationPythonAllOfTargets {
    pub fn new(module: String) -> ConfigApplicationPythonAllOfTargets {
        ConfigApplicationPythonAllOfTargets {
            module,
            callable: None,
            prefix: None,
        }
    }
}
