/*
 * NGINX Unit 1.31.1
 *
 * NGINX Unit is a lightweight and versatile application runtime that provides the essential components for your web application as a single open-source server: running application code, serving static assets, handling TLS and request routing.   **Important**: Ufnit's API is designed to expose any part of its configuration as an addressable endpoint.  Suppose a JSON object is stored at `/config/listeners/`:   ```json { \"*:8080\": { \"pass\": \"applications/wp_emea_dev\" } } ```  Here, `/config/listeners/_*:8080` and `/config/listeners/_*:8080/pass` are also endpoints.  Generally, object options are addressable by their names, array items—by their indexes (`/array/0/`).    **Note**: By default, Unit is configured through a UNIX domain socket. To use this specification with OpenAPI tools interactively, [start](https://unit.nginx.org/howto/source/#source-startup) Unit with a TCP port as the control socket.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: unit-owner@nginx.org
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfigApplicationJavaAllOf {
    /// Pathname of the application’s .war file (packaged or unpackaged).
    #[serde(rename = "webapp")]
    pub webapp: String,
    /// An array of strings.
    #[serde(rename = "classpath", skip_serializing_if = "Option::is_none")]
    pub classpath: Option<Vec<String>>,
    /// An array of strings.
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<String>>,
    /// Stack size of a worker thread in bytes.
    #[serde(rename = "thread_stack_size", skip_serializing_if = "Option::is_none")]
    pub thread_stack_size: Option<i32>,
    /// Number of worker threads per app process.
    #[serde(rename = "threads", skip_serializing_if = "Option::is_none")]
    pub threads: Option<i32>,
}

impl ConfigApplicationJavaAllOf {
    pub fn new(webapp: String) -> ConfigApplicationJavaAllOf {
        ConfigApplicationJavaAllOf {
            webapp,
            classpath: None,
            options: None,
            thread_stack_size: None,
            threads: None,
        }
    }
}
