/*
 * NGINX Unit 1.31.1
 *
 * NGINX Unit is a lightweight and versatile application runtime that provides the essential components for your web application as a single open-source server: running application code, serving static assets, handling TLS and request routing.   **Important**: Ufnit's API is designed to expose any part of its configuration as an addressable endpoint.  Suppose a JSON object is stored at `/config/listeners/`:   ```json { \"*:8080\": { \"pass\": \"applications/wp_emea_dev\" } } ```  Here, `/config/listeners/_*:8080` and `/config/listeners/_*:8080/pass` are also endpoints.  Generally, object options are addressable by their names, array items—by their indexes (`/array/0/`).    **Note**: By default, Unit is configured through a UNIX domain socket. To use this specification with OpenAPI tools interactively, [start](https://unit.nginx.org/howto/source/#source-startup) Unit with a TCP port as the control socket.
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: unit-owner@nginx.org
 * Generated by: https://openapi-generator.tech
 */

/// StatusConnections : Represents Unit's per-instance connection statistics.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StatusConnections {
    /// Total accepted connections during the instance’s lifetime.
    #[serde(rename = "accepted", skip_serializing_if = "Option::is_none")]
    pub accepted: Option<i32>,
    /// Current active connections for the instance.
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<i32>,
    /// Current idle connections for the instance.
    #[serde(rename = "idle", skip_serializing_if = "Option::is_none")]
    pub idle: Option<i32>,
    /// Total closed connections during the instance’s lifetime.
    #[serde(rename = "closed", skip_serializing_if = "Option::is_none")]
    pub closed: Option<i32>,
}

impl StatusConnections {
    /// Represents Unit's per-instance connection statistics.
    pub fn new() -> StatusConnections {
        StatusConnections {
            accepted: None,
            active: None,
            idle: None,
            closed: None,
        }
    }
}
